package io.nti.jaxrs.impl.generated;

/**
 * This code was generated by the JAX-RS annotation processor
 */

import io.nti.jaxrs.JaxRSServlet;

import javax.annotation.Generated;

@Generated("ServletProcessor")
public class GeneratedServlet extends JaxRSServlet {

    public GeneratedServlet() {
        super();
        addResource(new io.nti.jaxrs.impl.generated.ResourceInputProxy());

    }
}