package {{ package }};

/**
 * This code was generated by the JAX-RS annotation processor
 */

import io.nti.jaxrs.JaxRSServlet;

import javax.annotation.Generated;

@Generated("{{ generator }}")
public class {{ class }} extends JaxRSServlet {

    public {{ class }}() {
        super();
        {% for resource in resources %}addResource(new {{ resource }}());
        {% endfor %}

    }
}